import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { ThemeProvider } from "@/components/theme-provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: ReactNode;
}>;

export default function RootLayout({
  children,
}:RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <main>
          <ThemeProvider 
          attribute={"class"}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>

        {children}
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
